name:                Chapter07
version:             0.1.0.0
github:              "githubuser/Chapter07"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Chapter07#readme>

dependencies:
- base >= 4.7 && < 5
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Fork-exe:
    main:                Main.hs
    source-dirs:         app/Fork
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  Reminders-exe:
    main:                Main.hs
    source-dirs:         app/Reminders
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  MVar1-exe:
    main:                Main.hs
    source-dirs:         app/MVar1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  MVar2-exe:
    main:                Main.hs
    source-dirs:         app/MVar2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  MVar3-exe:
    main:                Main.hs
    source-dirs:         app/MVar3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  Logger-exe:
    main:                Main.hs
    source-dirs:         app/Logger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  PhoneBook-exe:
    main:                Main.hs
    source-dirs:         app/PhoneBook
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

  Chan-exe:
    main:                Main.hs
    source-dirs:         app/Chan
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07

tests:
  Chapter07-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter07
